# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T09:51:00+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, RootModel, conint, constr


class AccessDeniedException(RootModel[Any]):
    root: Any


class CancelJobRequest(BaseModel):
    pass


class CancellationStatus(Enum):
    CANCELLING = 'CANCELLING'
    CANCELLED = 'CANCELLED'


class CompressionType(Enum):
    NONE = 'NONE'
    GZIP = 'GZIP'


class ConflictException(RootModel[Any]):
    root: Any


class CreateJobRequestJobNameString(
    RootModel[
        constr(
            pattern=r'^[a-zA-Z0-9](-*[a-zA-Z0-9]){0,50}$', min_length=1, max_length=50
        )
    ]
):
    root: constr(
        pattern=r'^[a-zA-Z0-9](-*[a-zA-Z0-9]){0,50}$', min_length=1, max_length=50
    )


class CreateQuantumTaskRequestDeviceParametersString(
    RootModel[constr(min_length=1, max_length=48000)]
):
    root: constr(min_length=1, max_length=48000)


class CreateQuantumTaskRequestOutputS3BucketString(
    RootModel[constr(min_length=3, max_length=63)]
):
    root: constr(min_length=3, max_length=63)


class CreateQuantumTaskRequestOutputS3KeyPrefixString(
    RootModel[constr(min_length=1, max_length=1024)]
):
    root: constr(min_length=1, max_length=1024)


class CreateQuantumTaskRequestShotsLong(RootModel[conint(ge=0)]):
    root: conint(ge=0)


class DeviceArn(RootModel[constr(min_length=1, max_length=256)]):
    root: constr(min_length=1, max_length=256)


class DeviceOfflineException(RootModel[Any]):
    root: Any


class DeviceRetiredException(RootModel[Any]):
    root: Any


class DeviceStatus(Enum):
    ONLINE = 'ONLINE'
    OFFLINE = 'OFFLINE'
    RETIRED = 'RETIRED'


class DeviceType(Enum):
    QPU = 'QPU'
    SIMULATOR = 'SIMULATOR'


class GetDeviceRequest(BaseModel):
    pass


class GetJobRequest(BaseModel):
    pass


class GetJobResponseJobNameString(
    RootModel[
        constr(
            pattern=r'^[a-zA-Z0-9](-*[a-zA-Z0-9]){0,50}$', min_length=1, max_length=50
        )
    ]
):
    root: constr(
        pattern=r'^[a-zA-Z0-9](-*[a-zA-Z0-9]){0,50}$', min_length=1, max_length=50
    )


class GetQuantumTaskRequest(BaseModel):
    pass


class HyperParametersValueString(RootModel[constr(min_length=1, max_length=2500)]):
    root: constr(min_length=1, max_length=2500)


class InputFileConfigChannelNameString(
    RootModel[constr(pattern=r'^[A-Za-z0-9\.\-_]+$', min_length=1, max_length=64)]
):
    root: constr(pattern=r'^[A-Za-z0-9\.\-_]+$', min_length=1, max_length=64)


class InstanceConfigInstanceCountInteger(RootModel[conint(ge=1)]):
    root: conint(ge=1)


class InstanceConfigVolumeSizeInGbInteger(RootModel[conint(ge=1)]):
    root: conint(ge=1)


class InstanceType(Enum):
    ml_m4_xlarge = 'ml.m4.xlarge'
    ml_m4_2xlarge = 'ml.m4.2xlarge'
    ml_m4_4xlarge = 'ml.m4.4xlarge'
    ml_m4_10xlarge = 'ml.m4.10xlarge'
    ml_m4_16xlarge = 'ml.m4.16xlarge'
    ml_g4dn_xlarge = 'ml.g4dn.xlarge'
    ml_g4dn_2xlarge = 'ml.g4dn.2xlarge'
    ml_g4dn_4xlarge = 'ml.g4dn.4xlarge'
    ml_g4dn_8xlarge = 'ml.g4dn.8xlarge'
    ml_g4dn_12xlarge = 'ml.g4dn.12xlarge'
    ml_g4dn_16xlarge = 'ml.g4dn.16xlarge'
    ml_m5_large = 'ml.m5.large'
    ml_m5_xlarge = 'ml.m5.xlarge'
    ml_m5_2xlarge = 'ml.m5.2xlarge'
    ml_m5_4xlarge = 'ml.m5.4xlarge'
    ml_m5_12xlarge = 'ml.m5.12xlarge'
    ml_m5_24xlarge = 'ml.m5.24xlarge'
    ml_c4_xlarge = 'ml.c4.xlarge'
    ml_c4_2xlarge = 'ml.c4.2xlarge'
    ml_c4_4xlarge = 'ml.c4.4xlarge'
    ml_c4_8xlarge = 'ml.c4.8xlarge'
    ml_p2_xlarge = 'ml.p2.xlarge'
    ml_p2_8xlarge = 'ml.p2.8xlarge'
    ml_p2_16xlarge = 'ml.p2.16xlarge'
    ml_p3_2xlarge = 'ml.p3.2xlarge'
    ml_p3_8xlarge = 'ml.p3.8xlarge'
    ml_p3_16xlarge = 'ml.p3.16xlarge'
    ml_p3dn_24xlarge = 'ml.p3dn.24xlarge'
    ml_p4d_24xlarge = 'ml.p4d.24xlarge'
    ml_c5_xlarge = 'ml.c5.xlarge'
    ml_c5_2xlarge = 'ml.c5.2xlarge'
    ml_c5_4xlarge = 'ml.c5.4xlarge'
    ml_c5_9xlarge = 'ml.c5.9xlarge'
    ml_c5_18xlarge = 'ml.c5.18xlarge'
    ml_c5n_xlarge = 'ml.c5n.xlarge'
    ml_c5n_2xlarge = 'ml.c5n.2xlarge'
    ml_c5n_4xlarge = 'ml.c5n.4xlarge'
    ml_c5n_9xlarge = 'ml.c5n.9xlarge'
    ml_c5n_18xlarge = 'ml.c5n.18xlarge'


class Integer(RootModel[int]):
    root: int


class InternalServiceException(RootModel[Any]):
    root: Any


class JobArn(
    RootModel[constr(pattern=r'^arn:aws[a-z\-]*:braket:[a-z0-9\-]*:[0-9]{12}:job/.*$')]
):
    root: constr(pattern=r'^arn:aws[a-z\-]*:braket:[a-z0-9\-]*:[0-9]{12}:job/.*$')


class JobEventDetailsMessageString(RootModel[constr(min_length=0, max_length=2500)]):
    root: constr(min_length=0, max_length=2500)


class JobEventType(Enum):
    WAITING_FOR_PRIORITY = 'WAITING_FOR_PRIORITY'
    QUEUED_FOR_EXECUTION = 'QUEUED_FOR_EXECUTION'
    STARTING_INSTANCE = 'STARTING_INSTANCE'
    DOWNLOADING_DATA = 'DOWNLOADING_DATA'
    RUNNING = 'RUNNING'
    DEPRIORITIZED_DUE_TO_INACTIVITY = 'DEPRIORITIZED_DUE_TO_INACTIVITY'
    UPLOADING_RESULTS = 'UPLOADING_RESULTS'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'
    MAX_RUNTIME_EXCEEDED = 'MAX_RUNTIME_EXCEEDED'
    CANCELLED = 'CANCELLED'


class JobPrimaryStatus(Enum):
    QUEUED = 'QUEUED'
    RUNNING = 'RUNNING'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'
    CANCELLING = 'CANCELLING'
    CANCELLED = 'CANCELLED'


class JobStoppingConditionMaxRuntimeInSecondsInteger(
    RootModel[conint(ge=1, le=432000)]
):
    root: conint(ge=1, le=432000)


class JobToken(RootModel[constr(min_length=1, max_length=128)]):
    root: constr(min_length=1, max_length=128)


class JsonValue(RootModel[str]):
    root: str


class ListTagsForResourceRequest(BaseModel):
    pass


class Long(RootModel[int]):
    root: int


class QuantumTaskArn(RootModel[constr(min_length=1, max_length=256)]):
    root: constr(min_length=1, max_length=256)


class QuantumTaskStatus(Enum):
    CREATED = 'CREATED'
    QUEUED = 'QUEUED'
    RUNNING = 'RUNNING'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'
    CANCELLING = 'CANCELLING'
    CANCELLED = 'CANCELLED'


class ResourceNotFoundException(RootModel[Any]):
    root: Any


class RoleArn(
    RootModel[
        constr(pattern=r'^arn:aws[a-z\-]*:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+$')
    ]
):
    root: constr(pattern=r'^arn:aws[a-z\-]*:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+$')


class S3Path(
    RootModel[
        constr(pattern=r'^(https|s3)://([^/]+)/?(.*)$', min_length=0, max_length=1024)
    ]
):
    root: constr(pattern=r'^(https|s3)://([^/]+)/?(.*)$', min_length=0, max_length=1024)


class SearchDevicesFilterNameString(RootModel[constr(min_length=1, max_length=64)]):
    root: constr(min_length=1, max_length=64)


class SearchDevicesRequestMaxResultsInteger(RootModel[conint(ge=1, le=100)]):
    root: conint(ge=1, le=100)


class SearchJobsFilterOperator(Enum):
    LT = 'LT'
    LTE = 'LTE'
    EQUAL = 'EQUAL'
    GT = 'GT'
    GTE = 'GTE'
    BETWEEN = 'BETWEEN'
    CONTAINS = 'CONTAINS'


class SearchJobsRequestMaxResultsInteger(RootModel[conint(ge=1, le=100)]):
    root: conint(ge=1, le=100)


class SearchQuantumTasksFilterOperator(Enum):
    LT = 'LT'
    LTE = 'LTE'
    EQUAL = 'EQUAL'
    GT = 'GT'
    GTE = 'GTE'
    BETWEEN = 'BETWEEN'


class SearchQuantumTasksRequestMaxResultsInteger(RootModel[conint(ge=1, le=100)]):
    root: conint(ge=1, le=100)


class ServiceQuotaExceededException(RootModel[Any]):
    root: Any


class String(RootModel[str]):
    root: str


class String1024(RootModel[constr(min_length=1, max_length=1024)]):
    root: constr(min_length=1, max_length=1024)


class String2048(RootModel[constr(min_length=1, max_length=2048)]):
    root: constr(min_length=1, max_length=2048)


class String256(RootModel[constr(min_length=1, max_length=256)]):
    root: constr(min_length=1, max_length=256)


class String4096(RootModel[constr(min_length=1, max_length=4096)]):
    root: constr(min_length=1, max_length=4096)


class String64(RootModel[constr(min_length=1, max_length=64)]):
    root: constr(min_length=1, max_length=64)


class SyntheticTimestampDateTime(RootModel[datetime]):
    root: datetime


class TagKeys(RootModel[List[String]]):
    root: List[String]


class TagResourceResponse(BaseModel):
    pass


class TagsMap(RootModel[Optional[Dict[str, String]]]):
    root: Optional[Dict[str, String]] = None


class ThrottlingException(RootModel[Any]):
    root: Any


class UntagResourceRequest(BaseModel):
    pass


class UntagResourceResponse(BaseModel):
    pass


class Uri(
    RootModel[
        constr(
            pattern=r'\d{10,14}\.dkr\.ecr.[a-z0-9-]+\.amazonaws\.com\/.+(@sha256)?:.+',
            min_length=1,
            max_length=255,
        )
    ]
):
    root: constr(
        pattern=r'\d{10,14}\.dkr\.ecr.[a-z0-9-]+\.amazonaws\.com\/.+(@sha256)?:.+',
        min_length=1,
        max_length=255,
    )


class ValidationException(RootModel[Any]):
    root: Any


class CheckpointConfig(BaseModel):
    localPath: Optional[String4096] = None
    s3Uri: Optional[S3Path] = None


class DeviceConfig1(BaseModel):
    device: Optional[String256] = None


class InstanceConfig1(BaseModel):
    instanceCount: Optional[InstanceConfigInstanceCountInteger] = None
    instanceType: Optional[InstanceType] = None
    volumeSizeInGb: Optional[InstanceConfigVolumeSizeInGbInteger] = None


class OutputDataConfig(BaseModel):
    kmsKeyId: Optional[String2048] = None
    s3Path: Optional[S3Path] = None


class StoppingCondition(BaseModel):
    maxRuntimeInSeconds: Optional[JobStoppingConditionMaxRuntimeInSecondsInteger] = None


class QuantumTaskPostRequest(BaseModel):
    action: str = Field(..., description='The action associated with the task.')
    clientToken: constr(min_length=1, max_length=64) = Field(
        ..., description='The client token associated with the request.'
    )
    deviceArn: constr(min_length=1, max_length=256) = Field(
        ..., description='The ARN of the device to run the task on.'
    )
    deviceParameters: Optional[constr(min_length=1, max_length=48000)] = Field(
        None, description='The parameters for the device to run the task on.'
    )
    jobToken: Optional[constr(min_length=1, max_length=128)] = Field(
        None,
        description='The token for an Amazon Braket job that associates it with the quantum task.',
    )
    outputS3Bucket: constr(min_length=3, max_length=63) = Field(
        ..., description='The S3 bucket to store task result files in.'
    )
    outputS3KeyPrefix: constr(min_length=1, max_length=1024) = Field(
        ...,
        description='The key prefix for the location in the S3 bucket to store task results in.',
    )
    shots: conint(ge=0) = Field(
        ..., description='The number of shots to use for the task.'
    )
    tags: Optional[Dict[str, String]] = Field(
        None, description="Tags to be added to the quantum task you're creating."
    )


class QuantumTaskQuantumTaskArnCancelPutRequest(BaseModel):
    clientToken: constr(min_length=1, max_length=64) = Field(
        ..., description='The client token associated with the request.'
    )


class TagsResourceArnPostRequest(BaseModel):
    tags: Dict[str, String] = Field(
        ..., description='Specify the tags to add to the resource.'
    )


class CancelJobResponse(BaseModel):
    cancellationStatus: CancellationStatus
    jobArn: JobArn


class CancelQuantumTaskRequest(BaseModel):
    clientToken: String64


class CancelQuantumTaskResponse(BaseModel):
    cancellationStatus: CancellationStatus
    quantumTaskArn: QuantumTaskArn


class ContainerImage(BaseModel):
    uri: Uri


class CreateJobResponse(BaseModel):
    jobArn: JobArn


class CreateQuantumTaskRequest(BaseModel):
    action: JsonValue
    clientToken: String64
    deviceArn: DeviceArn
    deviceParameters: Optional[CreateQuantumTaskRequestDeviceParametersString] = None
    jobToken: Optional[JobToken] = None
    outputS3Bucket: CreateQuantumTaskRequestOutputS3BucketString
    outputS3KeyPrefix: CreateQuantumTaskRequestOutputS3KeyPrefixString
    shots: CreateQuantumTaskRequestShotsLong
    tags: Optional[TagsMap] = None


class CreateQuantumTaskResponse(BaseModel):
    quantumTaskArn: QuantumTaskArn


class DeviceConfig(BaseModel):
    device: String256


class DeviceSummary(BaseModel):
    deviceArn: DeviceArn
    deviceName: String
    deviceStatus: DeviceStatus
    deviceType: DeviceType
    providerName: String


class DeviceSummaryList(RootModel[List[DeviceSummary]]):
    root: List[DeviceSummary]


class GetDeviceResponse(BaseModel):
    deviceArn: DeviceArn
    deviceCapabilities: JsonValue
    deviceName: String
    deviceStatus: DeviceStatus
    deviceType: DeviceType
    providerName: String


class GetQuantumTaskResponse(BaseModel):
    createdAt: SyntheticTimestampDateTime
    deviceArn: DeviceArn
    deviceParameters: JsonValue
    endedAt: Optional[SyntheticTimestampDateTime] = None
    failureReason: Optional[String] = None
    jobArn: Optional[JobArn] = None
    outputS3Bucket: String
    outputS3Directory: String
    quantumTaskArn: QuantumTaskArn
    shots: Long
    status: QuantumTaskStatus
    tags: Optional[TagsMap] = None


class HyperParameters(RootModel[Optional[Dict[str, HyperParametersValueString]]]):
    root: Optional[Dict[str, HyperParametersValueString]] = None


class InstanceConfig(BaseModel):
    instanceCount: Optional[InstanceConfigInstanceCountInteger] = None
    instanceType: InstanceType
    volumeSizeInGb: InstanceConfigVolumeSizeInGbInteger


class JobCheckpointConfig(BaseModel):
    localPath: Optional[String4096] = None
    s3Uri: S3Path


class JobEventDetails(BaseModel):
    eventType: Optional[JobEventType] = None
    message: Optional[JobEventDetailsMessageString] = None
    timeOfEvent: Optional[SyntheticTimestampDateTime] = None


class JobEvents(RootModel[List[JobEventDetails]]):
    root: List[JobEventDetails] = Field(..., max_length=20, min_length=0)


class JobOutputDataConfig(BaseModel):
    kmsKeyId: Optional[String2048] = None
    s3Path: S3Path


class JobStoppingCondition(BaseModel):
    maxRuntimeInSeconds: Optional[JobStoppingConditionMaxRuntimeInSecondsInteger] = None


class JobSummary(BaseModel):
    createdAt: SyntheticTimestampDateTime
    device: String256
    endedAt: Optional[SyntheticTimestampDateTime] = None
    jobArn: JobArn
    jobName: String
    startedAt: Optional[SyntheticTimestampDateTime] = None
    status: JobPrimaryStatus
    tags: Optional[TagsMap] = None


class JobSummaryList(RootModel[List[JobSummary]]):
    root: List[JobSummary]


class ListTagsForResourceResponse(BaseModel):
    tags: Optional[TagsMap] = None


class QuantumTaskSummary(BaseModel):
    createdAt: SyntheticTimestampDateTime
    deviceArn: DeviceArn
    endedAt: Optional[SyntheticTimestampDateTime] = None
    outputS3Bucket: String
    outputS3Directory: String
    quantumTaskArn: QuantumTaskArn
    shots: Long
    status: QuantumTaskStatus
    tags: Optional[TagsMap] = None


class QuantumTaskSummaryList(RootModel[List[QuantumTaskSummary]]):
    root: List[QuantumTaskSummary]


class S3DataSource(BaseModel):
    s3Uri: S3Path


class ScriptModeConfig(BaseModel):
    compressionType: Optional[CompressionType] = None
    entryPoint: String
    s3Uri: S3Path


class SearchDevicesFilterValuesList(RootModel[List[String256]]):
    root: List[String256] = Field(..., max_length=10, min_length=1)


class SearchDevicesResponse(BaseModel):
    devices: DeviceSummaryList
    nextToken: Optional[String] = None


class SearchJobsFilterValuesList(RootModel[List[String256]]):
    root: List[String256] = Field(..., max_length=10, min_length=1)


class SearchJobsResponse(BaseModel):
    jobs: JobSummaryList
    nextToken: Optional[String] = None


class SearchQuantumTasksFilterValuesList(RootModel[List[String256]]):
    root: List[String256] = Field(..., max_length=10, min_length=1)


class SearchQuantumTasksResponse(BaseModel):
    nextToken: Optional[String] = None
    quantumTasks: QuantumTaskSummaryList


class TagResourceRequest(BaseModel):
    tags: TagsMap


class AlgorithmSpecification(BaseModel):
    containerImage: Optional[ContainerImage] = None
    scriptModeConfig: Optional[ScriptModeConfig] = None


class DataSource(BaseModel):
    s3DataSource: S3DataSource


class InputFileConfig(BaseModel):
    channelName: InputFileConfigChannelNameString
    contentType: Optional[String256] = None
    dataSource: DataSource


class SearchDevicesFilter(BaseModel):
    name: SearchDevicesFilterNameString
    values: SearchDevicesFilterValuesList


class SearchDevicesRequestFiltersList(RootModel[List[SearchDevicesFilter]]):
    root: List[SearchDevicesFilter] = Field(..., max_length=10, min_length=0)


class SearchJobsFilter(BaseModel):
    name: String64
    operator: SearchJobsFilterOperator
    values: SearchJobsFilterValuesList


class SearchJobsRequestFiltersList(RootModel[List[SearchJobsFilter]]):
    root: List[SearchJobsFilter] = Field(..., max_length=10, min_length=0)


class SearchQuantumTasksFilter(BaseModel):
    name: String64
    operator: SearchQuantumTasksFilterOperator
    values: SearchQuantumTasksFilterValuesList


class SearchQuantumTasksRequestFiltersList(RootModel[List[SearchQuantumTasksFilter]]):
    root: List[SearchQuantumTasksFilter] = Field(..., max_length=10, min_length=0)


class DevicesPostRequest(BaseModel):
    filters: List[SearchDevicesFilter] = Field(
        ...,
        description='The filter values to use to search for a device.',
        max_length=10,
        min_length=0,
    )
    maxResults: Optional[conint(ge=1, le=100)] = Field(
        None, description='The maximum number of results to return in the response.'
    )
    nextToken: Optional[str] = Field(
        None,
        description='A token used for pagination of results returned in the response. Use the token returned from the previous request continue results where the previous request ended.',
    )


class JobPostRequest(BaseModel):
    algorithmSpecification: AlgorithmSpecification = Field(
        ...,
        description='Defines the Amazon Braket job to be created. Specifies the container image the job uses and the paths to the Python scripts used for entry and training.',
    )
    checkpointConfig: Optional[CheckpointConfig] = Field(
        None,
        description='Contains information about the output locations for job checkpoint data.',
    )
    clientToken: constr(min_length=1, max_length=64) = Field(
        ...,
        description='A unique token that guarantees that the call to this API is idempotent.',
    )
    deviceConfig: DeviceConfig1 = Field(
        ...,
        description='Configures the quantum processing units (QPUs) or simulator used to create and run an Amazon Braket job.',
    )
    hyperParameters: Optional[Dict[str, HyperParametersValueString]] = Field(
        None,
        description='Algorithm-specific parameters used by an Amazon Braket job that influence the quality of the training job. The values are set with a string of JSON key:value pairs, where the key is the name of the hyperparameter and the value is the value of th hyperparameter.',
    )
    inputDataConfig: Optional[List[InputFileConfig]] = Field(
        None,
        description='A list of parameters that specify the name and type of input data and where it is located.',
        max_length=20,
        min_length=0,
    )
    instanceConfig: InstanceConfig1 = Field(
        ...,
        description='Configures the resource instances to use while running the Amazon Braket hybrid job on Amazon Braket.',
    )
    jobName: constr(
        pattern=r'^[a-zA-Z0-9](-*[a-zA-Z0-9]){0,50}$', min_length=1, max_length=50
    ) = Field(..., description='The name of the Amazon Braket job.')
    outputDataConfig: OutputDataConfig = Field(
        ...,
        description='Specifies the path to the S3 location where you want to store job artifacts and the encryption key used to store them.',
    )
    roleArn: constr(
        pattern=r'^arn:aws[a-z\-]*:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+$'
    ) = Field(
        ...,
        description="The Amazon Resource Name (ARN) of an IAM role that Amazon Braket can assume to perform tasks on behalf of a user. It can access user resources, run an Amazon Braket job container on behalf of user, and output resources to the users' s3 buckets.",
    )
    stoppingCondition: Optional[StoppingCondition] = Field(
        None, description='Specifies limits for how long an Amazon Braket job can run. '
    )
    tags: Optional[Dict[str, String]] = Field(
        None,
        description='A tag object that consists of a key and an optional value, used to manage metadata for Amazon Braket resources.',
    )


class JobsPostRequest(BaseModel):
    filters: List[SearchJobsFilter] = Field(
        ...,
        description='The filter values to use when searching for a job.',
        max_length=10,
        min_length=0,
    )
    maxResults: Optional[conint(ge=1, le=100)] = Field(
        None, description='The maximum number of results to return in the response.'
    )
    nextToken: Optional[str] = Field(
        None,
        description='A token used for pagination of results returned in the response. Use the token returned from the previous request to continue results where the previous request ended.',
    )


class QuantumTasksPostRequest(BaseModel):
    filters: List[SearchQuantumTasksFilter] = Field(
        ...,
        description='Array of <code>SearchQuantumTasksFilter</code> objects.',
        max_length=10,
        min_length=0,
    )
    maxResults: Optional[conint(ge=1, le=100)] = Field(
        None, description='Maximum number of results to return in the response.'
    )
    nextToken: Optional[str] = Field(
        None,
        description='A token used for pagination of results returned in the response. Use the token returned from the previous request continue results where the previous request ended.',
    )


class CreateJobRequestInputDataConfigList(RootModel[List[InputFileConfig]]):
    root: List[InputFileConfig] = Field(..., max_length=20, min_length=0)


class InputConfigList(RootModel[List[InputFileConfig]]):
    root: List[InputFileConfig]


class SearchDevicesRequest(BaseModel):
    filters: SearchDevicesRequestFiltersList
    maxResults: Optional[SearchDevicesRequestMaxResultsInteger] = None
    nextToken: Optional[String] = None


class SearchJobsRequest(BaseModel):
    filters: SearchJobsRequestFiltersList
    maxResults: Optional[SearchJobsRequestMaxResultsInteger] = None
    nextToken: Optional[String] = None


class SearchQuantumTasksRequest(BaseModel):
    filters: SearchQuantumTasksRequestFiltersList
    maxResults: Optional[SearchQuantumTasksRequestMaxResultsInteger] = None
    nextToken: Optional[String] = None


class CreateJobRequest(BaseModel):
    algorithmSpecification: AlgorithmSpecification
    checkpointConfig: Optional[JobCheckpointConfig] = None
    clientToken: String64
    deviceConfig: DeviceConfig
    hyperParameters: Optional[HyperParameters] = None
    inputDataConfig: Optional[CreateJobRequestInputDataConfigList] = None
    instanceConfig: InstanceConfig
    jobName: CreateJobRequestJobNameString
    outputDataConfig: JobOutputDataConfig
    roleArn: RoleArn
    stoppingCondition: Optional[JobStoppingCondition] = None
    tags: Optional[TagsMap] = None


class GetJobResponse(BaseModel):
    algorithmSpecification: AlgorithmSpecification
    billableDuration: Optional[Integer] = None
    checkpointConfig: Optional[JobCheckpointConfig] = None
    createdAt: SyntheticTimestampDateTime
    deviceConfig: Optional[DeviceConfig] = None
    endedAt: Optional[SyntheticTimestampDateTime] = None
    events: Optional[JobEvents] = None
    failureReason: Optional[String1024] = None
    hyperParameters: Optional[HyperParameters] = None
    inputDataConfig: Optional[InputConfigList] = None
    instanceConfig: InstanceConfig
    jobArn: JobArn
    jobName: GetJobResponseJobNameString
    outputDataConfig: JobOutputDataConfig
    roleArn: RoleArn
    startedAt: Optional[SyntheticTimestampDateTime] = None
    status: JobPrimaryStatus
    stoppingCondition: Optional[JobStoppingCondition] = None
    tags: Optional[TagsMap] = None
